version: '3.7'
services:
  server:
    build: ./front-end
    ports:
      - '8080:80'
    networks: 
        - api
  backend:
    build: ./backend
    ports:
        - "3001:3001"
    networks: 
        - api
networks: 
    api:
