version: "3.7"

services:
  backend-dev:
    restart: always
    build:
      context: ./back-end/
      dockerfile: dev.Dockerfile
    volumes:
      - ./back-end:/back-end
    networks:
      - api
    environment: 
      - PORT=8080
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    restart: always
    networks:
      - api
networks:
  api:
